#!/bin/bash


## smart contracts for test
# solc-select use 0.4.26
python script.py ./contract/check/case1.sol CompanyToken -m i -d c
python script.py ./contract/check/case2.sol MyBasketToken -m i -d c
python script.py ./contract/check/case3.sol FibonacciBalance -m i -d c
python script.py ./contract/check/case4.sol Missing -m i -d c
python script.py ./contract/check/case5.sol Missing -m i -d c
python script.py ./contract/check/case6.sol JM2020Token -m i -d c
python script.py ./contract/check/case7.sol OMGPool -m i -d c
python script.py ./contract/check/case8.sol Missing -m i -d c
python script.py ./contract/check/case9.sol TestContract -m i -d c
python script.py ./contract/check/case10.sol MyContract -m i  -d c
python script.py ./contract/check/case11.sol Phishable -m i -d c
python script.py ./contract/check/case12.sol Proxy -m i -d c
python script.py ./contract/check/case13.sol SimpleSuicide -m i -d c
python script.py ./contract/check/case14.sol Unprotected -m i -d c
python script.py ./contract/check/case15.sol Wallet -m i -d c
python script.py ./contract/check/case16.sol Wallet -m i -d c
python script.py ./contract/check/case17.sol Wallet -m i -d c
python script.py ./contract/check/case18.sol IntegerOverflowMultiTxMultiFuncFeasible -m i -d c
python script.py ./contract/check/case19.sol IntegerOverflowMultiTxOneFuncFeasible -m i -d c
python script.py ./contract/check/case20.sol IntegerOverflowSingleTransaction -m i -d c
python script.py ./contract/check/case21.sol GuessTheRandomNumberChallenge -m i -d c
python script.py ./contract/check/case22.sol BlackJack -m i -d c
python script.py ./contract/check/case23.sol Lottery -m i -d c
python script.py ./contract/check/case24.sol LuckyDoubler -m i -d c
python script.py ./contract/check/case25.sol PredictTheBlockHashChallenge -m i -d c
python script.py ./contract/check/case26.sol RandomNumberGenerator -m i -d c
python script.py ./contract/check/case27.sol DosAuction -m i -d c
python script.py ./contract/check/case28.sol DosGas -m i -d c
python script.py ./contract/check/case29.sol DosNumber -m i -d c
python script.py ./contract/check/case30.sol DosOneFunc -m i -d c
python script.py ./contract/check/case31.sol Government  -m i -d c
python script.py ./contract/check/case32.sol OddEven -d c
python script.py ./contract/check/case33.sol OddsAndEvens -d c
python script.py ./contract/check/case34.sol Save -d c
python script.py ./contract/check/case35.sol EthTxOrderDependenceMinimal -m i -d c
python script.py ./contract/check/case36.sol FindThisHash  -m i -d c
python script.py ./contract/check/case37.sol CryptoRoulette -m i -d c
python script.py ./contract/check/case38.sol OpenAddressLottery -m i -d c
python script.py ./contract/check/case39.sol EtherLotto -m i -d c
python script.py ./contract/check/case40.sol Governmental -m i -d c
python script.py ./contract/check/case41.sol lottopollo -m i -d c
python script.py ./contract/check/case42.sol Roulette -m i -d c
python script.py ./contract/check/case43.sol ReturnValue -m i -d c
python script.py ./contract/check/case44.sol Caller -m i -d c
python script.py ./contract/check/case45.sol Lotto -m i -d c
python script.py ./contract/check/case46.sol SendBack -m i -d c
python script.py ./contract/check/case47.sol Lotto -m i -d c
python script.py ./contract/check/case48.sol KingOfTheEtherThrone -m i -d c
python script.py ./contract/check/case49.sol demo -m i -d c
python script.py ./contract/check/case50.sol airdrop -m i -d c
python script.py ./contract/check/case51.sol TokenBank -m i -d c
python script.py ./contract/check/case52.sol EtherGet -m i -d c
python script.py ./contract/check/case53.sol airPort -m i -d c
python script.py ./contract/check/case54.sol MultiplicatorX3 -m i -d c
python script.py ./contract/check/case55.sol EBU -m i -d c
python script.py ./contract/check/case56.sol PoCGame -m i -d c
python script.py ./contract/check/case57.sol daoPOLSKAtokens -m i -d c
python script.py ./contract/check/case58.sol VaultProxy  -m i -d c
python script.py ./contract/check/case59.sol keepMyEther -m i -d c
python script.py ./contract/check/case60.sol AirDropContract -m i -d c
python script.py ./contract/check/case61.sol DepositProxy -m i -d c
python script.py ./contract/check/case62.sol VaultProxy -m i -d c
python script.py ./contract/check/case63.sol WhaleGiveaway1 -m i -d c
python script.py ./contract/check/case64.sol WedIndex -m i -d c
python script.py ./contract/check/case65.sol WhaleGiveaway1 -m i -d c
python script.py ./contract/check/case66.sol TokenBank -m i -d c
python script.py ./contract/check/case67.sol airDrop -m i -d c
python script.py ./contract/check/case68.sol Freebie -m i -d c
python script.py ./contract/check/case69.sol DrainMe -m i -d c
python script.py ./contract/check/case70.sol HomeyJar -m i -d c
python script.py ./contract/check/case71.sol Delta -m i -d c
python script.py ./contract/check/case72.sol TokenBank -m i -d c
python script.py ./contract/check/case73.sol SimpleDAO -m i -d c
python script.py ./contract/check/case74.sol Reentrance -m i -d c
python script.py ./contract/check/case75.sol ReentrancyDAO -m i -d c
python script.py ./contract/check/case76.sol Reentrancy_cross_function -m i -d c
python script.py ./contract/check/case77.sol Reentrance -m i -d c
python script.py ./contract/check/case78.sol EtherStore -m i -d c
python script.py ./contract/check/case79.sol EtherBank -m i -d c
python script.py ./contract/check/case80.sol LedgerChannel -m i -d c
python script.py ./contract/check/case81.sol Reentrancy_bonus -m i -d c
python script.py ./contract/check/case82.sol WALLET -m i -d c
python script.py ./contract/check/case83.sol FreeEth -m i -d c
python script.py ./contract/check/case84.sol DEP_BANK -m i -d c
python script.py ./contract/check/case85.sol Private_Bank -m i -d c
python script.py ./contract/check/case86.sol MONEY_BOX -m i -d c
python script.py ./contract/check/case87.sol TokenBank -m i -d c
python script.py ./contract/check/case88.sol BANK_SAFE -m i -d c
python script.py ./contract/check/case89.sol Pie -m i -d c
python script.py ./contract/check/case90.sol PoCGame -m i -d c
python script.py ./contract/check/case91.sol Marriage -m i -d c
python script.py ./contract/check/case92.sol Pie -m i -d c
python script.py ./contract/check/case93.sol TownCrier -m i -d c
python script.py ./contract/check/case94.sol Random -m i -d c
python script.py ./contract/check/case95.sol PRIVATE_ETH_CELL -m i -d c
python script.py ./contract/check/case96.sol FiftyFlip -m i -d c
python script.py ./contract/check/case97.sol demo  -m i -d c
python script.py ./contract/check/case98.sol OKLGRaffle -m i -d c
python script.py ./contract/check/case99.sol Honey -m i -d c
python script.py ./contract/check/case100.sol StakingRewards -m i -d c
python script.py ./contract/check/case101.sol Random -m i -d c
python script.py ./contract/check/case102.sol BaseFilterV1 -m i -d c
python script.py ./contract/check/case103.sol StakingRewardsFactory -m i -d c
python script.py ./contract/check/case104.sol PrivateBank -m i -d c
python script.py ./contract/check/case105.sol BaseFilterV1 -m i -d c
python script.py ./contract/check/case106.sol XPAY -m i -d c
python script.py ./contract/check/case107.sol x32323 -m i -d c
python script.py ./contract/check/case108.sol canNotDeclassify -m i -d c
python script.py ./contract/check/case109.sol InfiniteGold  -m i -d c
python script.py ./contract/check/case110.sol SuicideMultiTxFeasible -m i -d c
python script.py ./contract/check/case111.sol TokenGameHub -m i -d c
python script.py ./contract/check/case112.sol EtherBank -m i -d c
python script.py ./contract/check/case113.sol HelpMeSave -d c
python script.py ./contract/check/case114.sol HelpMeSave -d c
python script.py ./contract/check/case115.sol MGN -m i -d c
python script.py ./contract/check/case116.sol HitexToken -m i -d c
python script.py ./contract/check/case117.sol MGN -m i -d c
python script.py ./contract/check/case118.sol WEBVUA -m i -d c
python script.py ./contract/check/case119.sol PrivateBank -m i -d c
python script.py ./contract/check/case120.sol ETH_VAULT -m i -d c
python script.py ./contract/check/case121.sol PAPA -m i -d c
python script.py ./contract/check/case122.sol ClimateChangeCoin -m i -d c
python script.py ./contract/check/case123.sol VotePumpCoin0x -m i -d c
python script.py ./contract/check/case124.sol HELPToken -m i -d c
python script.py ./contract/check/case125.sol VIT -m i -d c
python script.py ./contract/check/case126.sol GlobexCrowdsale -m i -d c
python script.py ./contract/check/case127.sol TVTToken -m i -d c
python script.py ./contract/check/case128.sol HexaChain -m i -d c
python script.py ./contract/check/case129.sol U_BANK -m i -d c
python script.py ./contract/check/case130.sol PT -m i -d c
python script.py ./contract/check/case131.sol RobotBTC -m i -d c
python script.py ./contract/check/case132.sol cashtr -m i -d c
python script.py ./contract/check/case133.sol PENNY_BY_PENNY -m i -d c
python script.py ./contract/check/case134.sol ERC223Token  -m i -d c
python script.py ./contract/check/case135.sol AccessoryWrapper721 -m i -d c
python script.py ./contract/check/case136.sol BitLoanex -m i -d c
python script.py ./contract/check/case137.sol Morze -m i -d c
python script.py ./contract/check/case138.sol Hotto -m i -d c
python script.py ./contract/check/case139.sol CSBX -m i -d c
python script.py ./contract/check/case140.sol iBird -m i -d c
python script.py ./contract/check/case141.sol SACO -m i -d c
python script.py ./contract/check/case142.sol HELPToken -m i -d c
python script.py ./contract/check/case143.sol SELFDROPICO -m i -d c
python script.py ./contract/check/case144.sol ETH_FUND -m i -d c
python script.py ./contract/check/case145.sol KitFutureToken -m i -d c
python script.py ./contract/check/case146.sol PCC -m i -d c
python script.py ./contract/check/case147.sol DigiDollar -m i -d c
python script.py ./contract/check/case148.sol UEXCloudToken -m i -d c
python script.py ./contract/check/case149.sol UnicornCrowdsale -m i -d c
python script.py ./contract/check/case150.sol NewIntelTechMedia -m i -d c
python script.py ./contract/check/case151.sol MEDELIN -m i -d c
python script.py ./contract/check/case152.sol ERCDDAToken -m i -d c
python script.py ./contract/check/case153.sol XBORNID -m i -d c
python script.py ./contract/check/case154.sol Globextoken -m i -d c
python script.py ./contract/check/case155.sol PERSONAL_BANK -m i -d c
python script.py ./contract/check/case156.sol Market_Price -m i -d c
python script.py ./contract/check/case157.sol PrinCoin -m i -d c
python script.py ./contract/check/case158.sol GammaToken -m i -d c
python script.py ./contract/check/case159.sol CleanFoodCrypto -m i -d c
python script.py ./contract/check/case160.sol DCSToken -m i -d c
python script.py ./contract/check/case161.sol GLBX  -m i -d c
python script.py ./contract/check/case162.sol LuckyNumberImp -m i -d c
python script.py ./contract/check/case163.sol PRIT -m i -d c
python script.py ./contract/check/case164.sol Bitrich -m i -d c
python script.py ./contract/check/case165.sol X_WALLET -m i -d c
python script.py ./contract/check/case166.sol SmartEnergyToken -m i -d c
python script.py ./contract/check/case167.sol BECHAIN -m i -d c
python script.py ./contract/check/case168.sol ECR20HoneycombToken -m i -d c
python script.py ./contract/check/case169.sol Admc -m i -d c
python script.py ./contract/check/case170.sol CL -m i -d c
python script.py ./contract/check/case171.sol CRUDE -m i -d c
python script.py ./contract/check/case172.sol CROPSale -m i -d c
python script.py ./contract/check/case173.sol GTIX -m i -d c
python script.py ./contract/check/case174.sol DealGuard -m i -d c
python script.py ./contract/check/case175.sol QuChatToken -m i -d c
python script.py ./contract/check/case176.sol ETH_VAULT -m i -d c
python script.py ./contract/check/case177.sol METADOLLAR -m i -d c
python script.py ./contract/check/case178.sol BITRATETOKEN -m i -d c
python script.py ./contract/check/case179.sol RandomLedgerService -m i -d c
python script.py ./contract/check/case180.sol Asset -m i -d c
python script.py ./contract/check/case181.sol WangToken -m i -d c
python script.py ./contract/check/case182.sol BECEX -m i -d c
python script.py ./contract/check/case183.sol DNTC -m i -d c
python script.py ./contract/check/case184.sol MYSELF -m i -d c
python script.py ./contract/check/case185.sol BitmassExToken -m i -d c
python script.py ./contract/check/case186.sol OminiraProtocol -m i -d c
python script.py ./contract/check/case187.sol W_WALLET -m i -d c
python script.py ./contract/check/case188.sol GammaToken -m i -d c
python script.py ./contract/check/case189.sol MobileAppCoin -m i -d c
python script.py ./contract/check/case190.sol ECH  -m i -d c
python script.py ./contract/check/case191.sol BonusBank -m i -d c
python script.py ./contract/check/case192.sol MorphToken -m i -d c
python script.py ./contract/check/case193.sol StreamCashToken -m i -d c
python script.py ./contract/check/case194.sol  Hotto -m i -d c
python script.py ./contract/check/case195.sol  EtherCup -m i -d c
python script.py ./contract/check/case196.sol  MY_BANK -m i -d c
python script.py ./contract/check/case197.sol  LHOMME -m i -d c
python script.py ./contract/check/case198.sol PrivateDeposit -m i -d c
python script.py ./contract/check/case199.sol  JanusNetwork -m i -d c
python script.py ./contract/check/case200.sol  HumanErrorToken -m i -d c

exit
